Description: "Autoscaling group created by Terraform."
Resources:
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      Cooldown: 300
      HealthCheckType: EC2
      HealthCheckGracePeriod: 0
      LaunchConfigurationName: "${launch_configuration}"
      MinSize: "${min_size}"
      MaxSize: "${max_size}"
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupMinSize
            - GroupMaxSize
            - GroupDesiredCapacity
            - GroupInServiceInstances
            - GroupPendingInstances
            - GroupStandbyInstances
            - GroupTerminatingInstances
            - GroupTotalInstances
      Tags: ${tags}
      TerminationPolicies:
        - OldestLaunchConfiguration
        - OldestInstance
        - Default
      VPCZoneIdentifier: ${subnets}
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: "${min_size}"
        MaxBatchSize: "2"
        PauseTime: PT0S
Outputs:
  AsgId:
    Description: The id of the auto scaling group
    Value: !Ref AutoScalingGroup
